### PR TITLE
blob: allow to overwrite old or broken keys

### PR DESCRIPTION
**Pull request by bioothod**
Allow to overwrite old or broken keys (without BLOB_DISK_CTL_EXTHDR flag) with contiguous blocks

### CODE REVIEW

**Comment by shaitan** [comment]
Can you describe reason for continuity of writing blocks?

**Comment by bioothod** [comment]
Contiguous blocks overwrite file as a whole object in this case, i.e. going to replace it, not just overwrite some pieces of it (for example starting from some offset), thus it is safe to allow this.
It would not be the case for common write, but plain write started from the beginning is a sign of replacement, otherwise we would use common write with offset.

**Comment by bioothod** [comment]
I would actually remove that check at all.
If we call `prepare` then we are about to replace the whole file, then it is safe to overwrite old data which doesn't have external header

**Comment by bioothod** [comment]
Check removed, this commit allows plain write to overwrite old or broken records (without BLOB_DISK_CTL_EXTHDR flag), since prepare+plain_write is not used for partial update, prepare by itself a sign, that we are writing a new record and reserve space for it.

**Comment by bioothod** [comment]
Invalid approach, `eblob_write_prepare()` should fix flags instead

**Pull request closed without merging**
