### PR TITLE
Exception instead of error code

### PR DESCRIPTION
**Pull request by shaitan**
I've returned using exception instead of error code in eblob c++ binding and made messages of these exceptions in common style. Also I've fixed cpp tests.

### CODE REVIEW

**Comment by bioothod** [comment]
This still breaks API for older methods which returned 'int', is this ok with your guys?

**Comment by shaitan** [comment]
Yes it is ok, because all these methods returned 0 if them has been succeeded and threw exception in other cases. So these methods have never returned nonzero value and it should be ignored.

**Comment by bioothod** [comment]
Should I make new eblob (and elliptics) versions, or there will be new commits?

**Comment by shaitan** [comment]
Yes, I'm preparing 2-3 pull requests to eblob and elliptics.

**Pull request merged**
